### ISSUE TITLE
Inital pages

### ISSUE THREAD

**Issue by FriedrichAltheide** [monal-im/monal-im.org#1]
- [x] Home
- [x] Features
  * [x] Main features like Chatting, Groups, OMEMO Encryption
  * [x] (Partial) List of supported xeps (automaticaly created from doap file https://raw.githubusercontent.com/monal-im/Monal/develop/monal.doap)
- [x] Install
   * [x] Installation instructions
   * [x] Stable (AppStore)
   * [x] Beta (Testflight / Homebrew)
   * [x] Alpha 
- [x] Support
    * [x] XMPP MUC
    * [x] Github Issues
    * [x] Mail
- [x] Donate
- [x] Privacy
- [x] Blog

Partial language support for sites Privacy (englisch, german, ...)

**Comment by tmolitor-stud-tu** [comment]
can this be closed?

**Comment by wiseweb-works** [comment]
> can this be closed?

I just double-checked again. We have created more pages and content, what we need for this “Issue”. I think it can be closed. If we require a new page or content, it would be more appropriate to open a new issue.
