### ISSUE TITLE
Article: Reasons that make an XMPP client running on proprietary systems crucial

### ISSUE THREAD

**Issue by sjehuda** [monal-im/monal-im.org#52]
I suggest to add an article on that subject.

_Note: Even though Monal *can* be run on any system which supports the APIs that Monal use, it is mostly utilized on proprietary systems and is likely intended *for* these systems._

Some people ask whether it would be better to ask people to migrate to DivestOS and Linux instead?

### Why not asking people to migrate to BSD, DivestOS, KolibriOS, Linux, ReactOS etc.?

* Not all programs are supported on Linux (there are some niches that are not covered on every system).
* Not all want to use Linux on all their PCs

#### Obvious and direct reasons

* Not all programs are supported on Linux (there are some niches that are not covered on every system).
* Not all want to use Linux on all their PCs

#### Wider and indirect reasons

* So you, DivestOS, postmarketOS, Linux people would not have to be bound to a centralized messaging system or a proprietary messaging client (or both) on your free and open source systems.

Please see `/coyim/coyim/issues/864` (hyperlink is not in use so that it would not be shown as reference on the subject referenced page).

P.S.
* A decade ago, I was using Monal when I had a 3GS device, which kept me using XMPP.
* Today, I use DivestOS and postmarketOS.
* Monal is *my* option to make it possible to *me* to communicate over XMPP with friends who use proprietary systems, which saves me the trouble of installing proprietary messaging clients or using centralized messaging systems (or both).

**Comment by sjehuda** [comment]
Here is a draft which needs to be shortened and slang words be removed.

## The Importance of Monal in Open Communications

### How Monal protects you and your friends who use only free software

Monal (an open-source XMPP/Jabber messaging client) has become increasingly significant in today’s digital communication world. Despite being developed principally for proprietary systems such as BRAND and BRAND, Monal plays a critical role in the open communications ecosystem.

The reasons for this importance include:

1. Open-Standard Protocol: Even though Monal was initially intended for proprietary systems, it utilizes an open-standard protocol (XMPP). An open standard enhances interoperability, allowing communication across different platforms and devices.

2. Privacy and Security: Monal supports modern XMPP features like OMEMO for end-to-end encryption, which is vital for securing private communications. Unlike some proprietary communication platforms, Monal doesn’t sell or share user data, which upholds the essence of open communication - free, private, and secure exchange of ideas.

3. Decentralization: The use of Monal encourages decentralization of data, emphasizing user control over their own information. This contrasts with many proprietary systems, which centralize data thereby creating a potential single point of failure or misuse.

4. Freedom of Choice: Even though it’s intended mainly for BRAND environment, Monal’s open-source nature allows to be ported or adapted for other platforms, giving users the choice to select the operating system they prefer.

5. Community Development and Collaboration: Lastly, Monal fosters open communication in its development process. Being open-source, it invites collaborators to improve and tailor its features, creating a vibrant, participatory community around it.

6. **Promoting Open Communications in Proprietary Environments: Monal, by making XMPP available on proprietary systems, indirectly protects users of free software systems from installing proprietary software that uses centralized communication platforms. Many people find themselves compelled to use proprietary communication platforms because they want to communicate with others who are on these platforms. By offering a secure and private open-source alternative on proprietary systems, Monal breaks this cycle. Users on free software systems can communicate with those on proprietary systems through Monal, without having to compromise their commitment to open software. This cross-platform communicability strengthens the open communication ecosystem.**

With this valuable addition, it’s even clearer that Monal plays an essential role in promoting open communications. Whether for proprietary or free software systems, Monal provides a secure, decentralized, and user-friendly platform for seamless communication.

In conclusion, Monal’s importance for open communication is beyond the boundary of proprietary systems. Its ethos and technical design prioritize open standards, privacy, decentralization, and freedom of choice. By doing so, it not only facilitates open communication but also encourages the community of users to participate, collaborate, and develop a more open communication environment.

For a visual representation of how Monal works and more about its features, please see the link below. 

Link to Monal’s official website

This article only touches upon the surface of Monal’s importance in open communications. If you wish to delve deeper into the world of open-source communication platforms, you should certainly explore and try out Monal. It has a lot to offer in terms of privacy, freedom, and cross-platform interoperability.

**Comment by Neustradamus** [comment]
Interesting ticket!

Note about CoyIM, it supports only OTR because he is one of OTRv4 team:
- https://www.google.com/search?q=%22otrv4+ola+bini%22

**Comment by sjehuda** [comment]
> Note about CoyIM, it supports only OTR because he is one of OTRv4 team.

Thank you. I did not know that.

I deeply appreciate the work on another XMPP client, and I also appreciate the work on OTR which is an encryption system that have been accompanying so much of us during the recent decade and even more than a decade, but they have to support other means or at least set a mechanism that would allow to set other means.

This article would hopefully persuade CoyIM to support this argument.

This article also explains why all of us should support Monal, never mind if you are using a proprietary OS or a person who wants to abolish those iBrand systems before tomorrow.
