### ISSUE TITLE
Fix remote image loading/caching

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/monal-im.org#61]
@wiseweb-works Could you please fix my commit over here: https://github.com/monal-im/monal-im.org/commit/a74061e08bd5923ab1d835a89a1eddbb72f3ac50

I want the image to be fetched when building the hugo website and served from our webserver after build. But somehow it doesn't work the way I want it to, but my hugo skills are too limited to fix that in a reasonable amount of time.

The commit is just an experiment, feel free to change everything if there is a better approach than that :)

Thanks!!

**Comment by wiseweb-works** [comment]
I got a notification via E-mail. I will check. 👍🏻
