### ISSUE TITLE
Blog post not appearing

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/monal-im.org#72]
Why does the blog post `00014-monal-internals-xml-query-language.md` in staging not appear on our github pages branch when building the site? Other changes properly propagate to github pages an can be viewed at https://monal-im.github.io/monal-im.org/site/ (for example renaming FAQ to Wiki in our menu).

**Comment by wiseweb-works** [comment]
I got a notification via E-mail. I will check. 👍🏻 @tmolitor-stud-tu

**Comment by tmolitor-stud-tu** [comment]
Great, many thanks!! :)
